### PR TITLE
Add translation for "Issues for child elements" heading

### PR DESCRIPTION
**Pull request by rumata28**
When there are issues found by lint rules on a Pool element, a header "Issues for child elements" is added, and that header is not translatable.

PS: I also fixed really minor typos in some of the code comments, and name of one local variable.

### CODE REVIEW

**Comment by barmac** [comment]
Hi, thanks for your submission. However, until you sign the CLA, we cannot look into the changes.

**Comment by rumata28** [comment]
Hi, signed it, but it is still "pending"///

**Comment by barmac** [comment]
It looks like you need to change the commits to use your GitHub email address: https://stackoverflow.com/questions/3042437/how-can-i-change-the-commit-author-for-a-single-commit
Notice that in the PR's commit history, your GitHub handle is not linked to the commits.

**Comment by rumata28** [comment]
yeah.. thanks.  updated commit e-mail to match my account.

**Review by nikku — APPROVED** [review]
Thanks, nice little fix, and good cleanups along the way, too!

**Comment by nikku** [comment]
Released via [v0.22.1](https://github.com/bpmn-io/bpmn-js-bpmnlint/releases/tag/v0.22.3).

**Pull request merged**
