### PR TITLE
add function getIssues

### PR DESCRIPTION
**Pull request by gogroup-official**

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
Please add [a test case](https://github.com/bpmn-io/bpmn-js-bpmnlint/blob/main/test/spec/LintingSpec.js) to verify this behavior.

**Comment by gogroup-official** [comment]
I think we dont need it

**Comment by nikku** [comment]
Thanks for your comment. I'll close this PR.

**Comment by nikku** [comment]
Happy to re-open + merge if you follow up with a test case. Once we add or change public API we want to ensure that is tested.

**Pull request closed without merging**
