### PR TITLE
chore(project): include source code in package

### PR DESCRIPTION
**Pull request by barmac**
This allows npm package users to subclass Linting instead of forcing to use a whole module.

### CODE REVIEW

**Comment by nikku** [comment]
What is the actual use case?

**Comment by barmac** [comment]
More or less this:

```javascript
import Linting from 'bpmn-js-bpmnlint/lib/Linting';
import LinterConfig from './.bpmnlintrc';

export default function CamundaModelerLinting(injector) {
  const locals = {
    'config.linting': {
      bpmnlint: LinterConfig
    }
  };

  injector.invoke(Linting, this, locals);
}

CamundaModelerLinting.$inject = [ 'injector' ];
```

**Comment by nikku** [comment]
What keeps you from using the [standard way](https://github.com/bpmn-io/bpmn-js-bpmnlint#usage) of passing the linter config?

**Comment by nikku** [comment]
The whole idea is to keep things configurable / plug-able.

**Comment by barmac** [comment]
In my use case, I am not able to pass custom config to Modeler. Still, I want to be able to actually use the module. To reveal more of my intentions, my ultimate goal is to use object getters to simply change the linter config in run time.

What is more, to apply currently any modifications, not only config related, to the module, I have to copy the code from repository and apply custom modifications in my project. Instead, I would like to be able to just import the base class and change what I need.

**Comment by nikku** [comment]
> In my use case, I am not able to pass custom config to Modeler. 

Please share an example of what you're trying to do. I'd like to understand it. Maybe we'd need to build a more appropriate solution.

**Comment by nikku** [comment]
Closing this issue due to missing feedback. Happy to re-open it if you provide the [desired input](https://github.com/bpmn-io/bpmn-js-bpmnlint/pull/9#issuecomment-476114081).

**Pull request closed without merging**
