### PR TITLE
Refactor plugin 2

### PR DESCRIPTION
**Pull request by nikku**
An updated version of `refactor-plugin`, [cf. changes](https://github.com/bpmn-io/bpmn-js-bpmnlint/compare/refactor-plugin...refactor-plugin-2?expand=1).

This version gets rid of a few quirks mentioned:

* Drop linking support for rules: We cannot reliably link to anything, other than bpmnlint core rules. Links contain meta-data though (rule and message) so that could be built on top of the tool or integrated at a later stage.
* Dropped JS dropdown tooltip handling. Done in plain CSS without any timeouts and other fancy features now.
* Handle canvas in the same way like other element overlays.
* Show rule name as title
* Make warning sign visually equal to error
* Simplify styles (drop super-long-prefix-to-restore-my-sanity)
* Simplify API
* Mark all private methods as private (cool idea!)

### CODE REVIEW

**Comment by philippfromme** [comment]
So it's basically like it was before. 😅

**Comment by nikku** [comment]
> So it's basically like it was before. sweat_smile

Haha, nope. I think we still carried out some improvements that are worth a new minor :wink:

**Comment by philippfromme** [comment]
I agree, no worries.
________________________________

**Comment by nikku** [comment]
I've also added a few new bugs, as it seems like.

:see_no_evil:

**Comment by philippfromme** [comment]
For consistency I assume.

**Pull request merged**
