### PR TITLE
feat(linting): Display root element warnings

### PR DESCRIPTION
**Pull request by ssternal**
While working with the linting plugin I've found a small mistake. Whenever you got child warnings on the root element, these are not displayed at all.

Before:

Before

After:

After

### CODE REVIEW

**Comment by barmac** [comment]
Hi,

Thanks for your contribution. Can you please add a test case which should notice if we break it in the future? Please feel free to check out the existing tests: https://github.com/bpmn-io/bpmn-js-bpmnlint/blob/master/test/spec/LintingSpec.js#L532

**Comment by ssternal** [comment]
Thanks for the quick reply. I will try to do so in next couple of days.

**Comment by ssternal** [comment]
I hope you got notified about the latest commit. In case there was none this comment should trigger one :)

**Comment by barmac** [comment]
Hi, thanks for notice. I will look into this today.

**Review by barmac — APPROVED** [review]
I've pushed a couple of changes:
* run `npm run lint -- --fix` to fix linting errors
* simplified and moved the test case to the overlays section (next to warning and error overlays tests)
* squashed the commits
* changed commit message to `fix` as it's a bugfix and not a feature

Thank you for your contribution! I will release it shortly.

**Pull request merged**
